= EasyRPG Editor
// hide ugly links behind atributes to not interrupt plain text flow
:docs: link:docs[docs folder]
:liblcf: https://github.com/EasyRPG/liblcf[liblcf]
:qt6: https://www.qt.io[Qt 6]
:translation: link:docs/Translation.adoc[Translation]
:irc-channel: https://kiwiirc.com/nextclient/#ircs://irc.libera.chat/#easyrpg?nick=rpgguest??
:authors-doc: link:docs/AUTHORS.adoc[AUTHORS document]
:copying-icons: link:docs/licenses/COPYING-ICONS[COPYING-ICONS]
// end of header

EasyRPG Editor is a game editor to create EasyRPG games. It can import
RPG Maker 2000 and 2003 games using liblcf to read RPG Maker game data.

EasyRPG Editor is part of the EasyRPG Project. More information is
available at the project website: https://easyrpg.org/


== Documentation

Documentation is available in the {docs} and at the documentation wiki:
https://wiki.easyrpg.org


== Requirements

- {liblcf} for RPG Maker data reading.
- {qt6} (>= 6.10.1) (Widgets, QtQuick/QML, Multimedia and SVG)
- ECM for additional CMake functionality.
- Kirigami for additional QML Widgets.
- QQC2 Breeze Style for QML styling.
- KDDockWidgets for floating windows and docking.
- zlib for XYZ image support.
- Glaze for converting LCF data to JSON and binding to QML.

Optional dependencies:

- Qt Linguist (optional, for translation)

== Daily builds

Up to date binaries for assorted platforms are available at our continuous
integration service:

https://ci.easyrpg.org/view/Editor/


== Source code

EasyRPG Editor development is hosted by GitHub, project files are available
in this git repository:

https://github.com/EasyRPG/Editor

Released versions are also available at our Download Archive:

https://easyrpg.org/downloads/editor/


== Building

Building requirements:

- A C++23 capable compiler.
- CMake >= 3.15 (>= 3.23 to use the provided CMake presets)

Step-by-step instructions:

[source,shell]
---------------------------------------
cmake -S . -B build   # generate the build system
cmake --build build   # compile the executable
---------------------------------------

Another option is to use CMake presets:

---------------------------------------
cmake --preset TYPE          # generate the build system
cmake --build --preset TYPE  # compile the executable
---------------------------------------

Possible values for `TYPE` are `debug`, `relwithdebinfo` and `release`.

If liblcf is not installed on the system, either add `-DEDITOR_BUILD_LIBLCF=ON`
to the configure step to build it as part of the project, or use one of the
`liblcf-TYPE` presets (e.g. `liblcf-debug`).

The non-Qt dependencies can be installed and built automatically with vcpkg.
This requires vcpkg to be installed and the `VCPKG_ROOT` environment variable
to be set to its installation directory. Due to its sheer size, Qt6 itself is
not managed by vcpkg and must still be provided separately (e.g. as a system
package). The corresponding presets are `vcpkg-TYPE` and `vcpkg-liblcf-TYPE`.


== Running EasyRPG Editor

Put the generated executable in the "bin" folder and launch it.


== Translating EasyRPG Editor

See {translation} document.


== Bug reporting

Available options:

* File an issue at https://github.com/EasyRPG/Editor/issues
* Open a thread at https://community.easyrpg.org/
* Chat with us via IRC: {irc-channel}[#easyrpg at irc.libera.chat]


== License

EasyRPG Editor is free software available under the GPLv3 license. See the file
link:COPYING[] for license conditions. For Author information see {authors-doc}.

=== 3rd party resources

The files in link:resources/icons[] are Breeze icons or derivates licensed under
LGPLv3. See the file {copying-icons} for license
conditions.
