= EasyRPG Editor
// hide ugly links behind atributes to not interrupt plain text flow
:docs: link:docs[docs folder]
:liblcf: https://github.com/EasyRPG/liblcf[liblcf]
:qt5: https://www.qt.io[Qt 5]
:translation: link:docs/Translation.adoc[Translation]
:irc-channel: https://kiwiirc.com/nextclient/#ircs://irc.libera.chat/#easyrpg?nick=rpgguest??
:authors-doc: link:docs/AUTHORS.adoc[AUTHORS document]
:copying-icons: link:docs/licenses/COPYING-ICONS[COPYING-ICONS]
// end of header

EasyRPG Editor is a game editor to create EasyRPG games. It can import
RPG Maker 2000 and 2003 games using liblcf to read RPG Maker game data.

EasyRPG Editor is part of the EasyRPG Project. More information is
available at the project website: https://easyrpg.org/


== Documentation

Documentation is available in the {docs} and at the documentation wiki:
https://wiki.easyrpg.org


== Requirements

- {liblcf} for RPG Maker data reading.
- {qt5} (>= 5.11)
- Qt Multimedia
- Qt SVG

== Daily builds

Up to date binaries for assorted platforms are available at our continuous
integration service:

https://ci.easyrpg.org/view/Editor/


== Source code

EasyRPG Editor development is hosted by GitHub, project files are available
in this git repository:

https://github.com/EasyRPG/Editor

Released versions are also available at our Download Archive:

https://easyrpg.org/downloads/editor/


== Building

Building requirements:

- CMake >= 3.15

Step-by-step instructions:

[source,shell]
---------------------------------------
cmake .        # generate Makefile
cmake --build  # compile the executable
---------------------------------------


== Running EasyRPG Editor

Put the generated executable in the "bin" folder and launch it.


== Translating EasyRPG Editor

See {translation} document.


== Bug reporting

Available options:

* File an issue at https://github.com/EasyRPG/Editor/issues
* Open a thread at https://community.easyrpg.org/
* Chat with us via IRC: {irc-channel}[#easyrpg at irc.libera.chat]


== License

EasyRPG Editor is free software available under the GPLv3 license. See the file
link:COPYING[] for license conditions. For Author information see {authors-doc}.

=== 3rd party resources

The files in link:resources/icons[] are Breeze icons or derivates licensed under
LGPLv3. See the file {copying-icons} for license
conditions.
